# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-17 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vertices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertex_json', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='marker',
            name='marker_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='file',
            field=models.FileField(null=True, upload_to='coord'),
        ),
    ]
